name: Latest Medium Articles
on:
  schedule:
    - cron: '0 0 * * *' # Once a day at 00:00
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Medium articles
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://alperonline.medium.com/feed"
          max_post_count: 5

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update latest Medium posts"
